travis:
  secure:
    BINSTAR_TOKEN: Cze0I8XFvcz6dCuavVDqBH/Qjho6W7C4Hm6hteSu7ylRRFkF+gaHX+4aA6Dalx6OIDD69QmOzd1BAozZUbTEYVW9iYFq6Gw0y7BEzECtruhB1vrCD2vRbdULs9P+f8fkn+ZUJrEhXAjkdV+z0DsYbr+aB3TWzK0Gyo5t5P26gmcnG6UNqK2dgdcDGO2xpfs+jCmhchICkUWC5vCFhY/HXd60C+Z7jvLpuLDlMmDMi3mjWXcJVhjgwXhWS1Ppi6m7faY6Y4emhaXtS4IfQ0FmGfr2lp+mGHZJWsyMry7TzcAjJfAb9ikoRGx8QOfJIQarp7YhMXMRFlBnzAlNVL/JV4YozMju9rqGKshfgt5DFyTpDXz0igfJkl8/xKZo+oF4TLMiiXgJ38/3cdPFQU4DVIhJGr5SIq4wkgQ2tU15XEJ6CeybfwzJfdx5bAKJvXFQHBqyf5UwVg85FJ7Pnltep+djpRZl5ELbcAKOL8E+bsx9r2ds1oipflvW/0XXBAhBk1H/AQmvNjpal2TDHAKxvGF/Mxxk4yzWRWXgqyR17qBotxW9i3x1D+++dcKQAg3R63YlpQCowmcSGcyYvyjIUkbCbgzKdRfnMwoT0ZIfLd5kZL91eXyiHLXyuFyrKB50PdaIezx6eyPL9+18ZDdeLmpDubGGhGsDvcIzmsebkXA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
